# This file contains the default values used to generate the config
# from the template when the existing config is missing nodes

auto-updater: true

use-tagapi: true

use-eventfilter: true

messages:
  please-wait-name: "Hang tight, it may take a moment to look up \xa7b%1$s\xa7r's name history..."
  erroneous-errors: "Sorry, something bad happened when we asked Mojang about \xa7c%1$s\xa7r"
  history-original: "\xa7b%1$s16\xa7r (\xa7ooriginal\xa7r)"
  history-historic: "\xa7b%1$s16\xa7r (%2$s)"
  history-realtime: "\xa7b%1$s16\xa7r (%2$s - \xa7ocurrent\xa7r)"

debug: false

version: 0
